routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

use App\Http\Controllers\reports\DynamicReportController;
use App\Http\Controllers\reports\ReportController;

Auth::routes();

// --- habilidades, roles, usuarios
Route::get('users-list', 'Admin\UserController@getAll');
Route::get('roles-list', 'Admin\RoleController@getAll');
Route::get('abilities-list', 'Admin\AbilityController@getAll');
//------------------------------------
Route::get('documents-list', 'DocumentController@getAll');
Route::get('scripts-list', 'ScriptController@getAll');
Route::get('devices-list', 'DeviceController@getAll');
Route::post('devices-save', 'DeviceController@save');
Route::post('devices-connect', 'DeviceController@connect');
Route::get('devices-tree-list', 'DeviceTreeController@getTree');

// --- Se crea un prefijo para eliminar el /admin/ de todas las url ---//
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::resource('/users', 'Admin\UserController');
    Route::resource('/roles', 'Admin\RoleController');
    Route::resource('/abilities', 'Admin\AbilityController');
});

// --- Se agrupan para aplicar el middleware de auth ---//
Route::middleware(['auth'])->group(function () {
    Route::get('tools', 'ToolController@index')->name('tools');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/user/profile', 'ProfileController@breadcrumb')->name('profile');
    Route::resource('documents', 'DocumentController');
    Route::resource('devices', 'DeviceController');
    Route::resource('scripts', 'ScriptController');
    /*
     * Trees
     */
    Route::resource('devices-tree', 'DeviceTreeController');
});

// --- Cambiar el lenguaje ---//
Route::get('lang/{locale}', 'LangController@index');
Route::post('document-image-upload', 'DocumentController@imageUpload')->name('image.upload');

// Modificacion de la imagen de perfil del usuario
Route::post('/modificar-img-perfil', 'ImageProfileController@test');

// Reports section
Route::get('/show_reports', [ReportController::class, 'homeReports']);

resources/views/devices.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Documentos</h4>-->

                @if (Auth::user()->can('documents_create'))
                    <div class="row">
                        <a href="{{ URL::route('devices.create') }}">
                            <button type="button" class="btn btn-rounded btn-primary">{{ __('Administrador') }}</button>
                        </a>
                    </div>                                   
                @endif

                <div class="row">
                    <div class="col">
                        <table 
                            class="table color-table table-responsive table-striped table-hover w-100 d-block d-md-table table-md" 
                            id="devices-table">    
                        </table>
                    </div>
                </div>                    
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/documents.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Documentos</h4>-->

                @if (Auth::user()->can('documents_create'))
                    <div class="row">
                        <a href="{{ URL::route('documents.create') }}">
                            <button type="button" class="btn btn-rounded btn-primary">Crear nuevo</button>
                        </a>
                    </div>                                   
                @endif

                <div class="row">
                    <div class="col">
                        <table 
                            class="table color-table table-responsive table-striped table-hover w-100 d-block d-md-table table-md" 
                            id="documents-table">    
                        </table>
                    </div>
                </div>                    
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/documents_create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title text-muted">Nuevo</h4>-->
                
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form class="form-material" method="POST" action="{{ route('documents.store') }}">

                        {{ csrf_field() }}

                        <div class="row">

                            <div class="col-12">
                                <input 
                                    style="font-size: 34px;" 
                                    type="text"
                                    class="form-control"
                                    id="title" 
                                    name="title" 
                                    placeholder="Escribe aquí el título"
                                    value="{{ old('title') }}" 
                                >
                            </div>
                            <div class="col-12">
                                <textarea style="font-size: 14px;" rows="3" class="form-control" name="description" id="description" placeholder="Aquí la descripción">{{ old('description') }}</textarea>
                            </div>
                            <!--
                            <div class="col-4">
                                <input type="text" class="form-control" id="tags" name="tags">
                            </div>
                            -->
                        </div>

                        <div class="w-100">&nbsp;</div>

                        <div class="row">
                            <div class="col">
                                <textarea id="content" name="content" class="summernote">{{ old('content') }}</textarea>
                            </div>  
                        </div>

                        <div class="row text-right">
                            <div class="col">
                                <button type="submit" class="btn btn-success" id="save">
                                    <i class=""></i> Guardar
                                </button>

                            </div>                                    
                        </div>

                    </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/documents_edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title text-muted">Nuevo</h4>-->

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form class="form-material" method="POST" action="{{ route('documents.update',$document->id) }}">

                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}

                        <div class="row">

                            <div class="col-12">
                                <input 
                                    style="font-size: 34px;" 
                                    type="text"
                                    class="form-control"
                                    id="title" 
                                    name="title"
                                    value="{{ old('title', $document->title) }}" 
                                    placeholder="Escribe aquí el título"
                                >
                            </div>
                            <div class="col-12">
                                <textarea style="font-size: 14px;" rows="3" class="form-control" name="description" id="description" placeholder="Aquí la descripción">{{ old('description', $document->description) }}</textarea>
                            </div>
                            <!--
                            <div class="col-4">
                                <input type="text" class="form-control" id="tags" name="tags" value="">
                            </div>
                            -->
                        </div>

                        <div class="w-100">&nbsp;</div>

                        <div class="row">
                            <div class="col">
                                <textarea id="content" name="content" class="summernote">{!! old('content', $document->content) !!}</textarea>
                            </div>  
                        </div>

                        <div class="row text-right">
                            <div class="col">
                                <button type="submit" class="btn btn-success" id="save">
                                    <i class=""></i> Guardar
                                </button>

                            </div>                                    
                        </div>

                    </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                My super application here :D
                            </div>
                        </div>
                    </div>
                </div>
@endsection

resources/views/scripts.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Scripts</h4>-->

                @if (Auth::user()->can('script_create'))
                    <div class="row">
                        <a href="{{ URL::route('scripts.create') }}">
                            <button type="button" class="btn btn-rounded btn-primary">Crear nuevo</button>
                        </a>
                    </div>
                @endif

                <div class="row">
                    <div class="col">
                        <table
                            class="table color-table table-responsive table-striped table-hover w-100 d-block d-md-table table-md"
                            id="scripts-table">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/scripts_create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">Nuevo scripts</h4>
                <h6 class="card-subtitle"> Ingresar un nuevo <code> scripts</code> y configurar sus parametros.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('scripts.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Capacidades de red"
                                id="name" name="name" value="{{ old('name') }}" require>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <textarea class="form-control" rows="3" id="description" name="description"
                                require>{{ old('description') }}</textarea>
                            <span class="help-block text-muted">
                                <small>Agregar una descripcion del script para identificar su funcionamiento.</small>
                            </span>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Tipo</label>
                        <div class="col-10">
                            <select class="form-control" id="type" name="type">
                                <option>SOAP</option>
                                <option>RESTful</option>
                                <option>SSH</option>
                                <option>Gearman</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">API</label>
                        <div class="col-10">
                            <select class="form-control" id="api" name="api">
                                <option>NuSOAP</option>
                                <option>SLIM</option>
                                <option>SSH2</option>
                            </select>
                        </div>
                    </div>
                    <!-- <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label">Autor</label>
                        <input type="text" class="form-control form-control-line" id="author" name="author"
                            placeholder="Autor">
                    </div> -->
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Version</label>
                        <div class="col-10">
                            <input type="numeric" class="form-control form-control-line" id="version" name="version"
                                placeholder="1.00" value="{{ old('version') }}" require>
                        </div>
                    </div>

                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Lenguaje</label>
                        <div class="col-10">
                            <select class="form-control" id="language" name="language">
                                <option>PHP</option>
                                <option>JAVA</option>
                                <option>C#</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">URL</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" id="url" name="url"
                                placeholder="http://localhost" value="{{ old('url') }}" require>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Template</label>
                        <div class="col-3">
                            <select class="form-control" id="template_id" name="template_id"
                                onchange="changeTemplate()">
                                <option value=""> Sin template </option>
                                @foreach ($templates as $template)
                                <option value="{{ $template }}"> {{ $template->name }} </option>
                                @endforeach
                            </select>
                        </div>
                        <label class="col-7 col-form-label" id="template_description"> </label>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Guardar
                            </button>
                            <a href="{{ route('scripts.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection




<!-- function changTemplate(obj) {
    var combo = document.getElementById("template_id");
    var selected = combo.options[combo.selectedIndex].value;
    var obj = JSON.parse(selected);
    document.getElementById('template_description').innerHTML = obj['description'];
} -->

resources/views/scripts_edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">Editar el scripts con el id: {{ $script->id }} </h4>
                <h6 class="card-subtitle"> Editar un <code> scripts</code> y configurar sus parametros.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('scripts.update', $script->id) }}">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Capacidades de red" id="name" name="name" value="{{ $script->name }}" require>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <textarea class="form-control" rows="3" id="description" name="description" require>{{ $script->description }}</textarea>
                            <span class="help-block text-muted">
                                <small>Agregar una descripcion del script para identificar su funcionamiento.</small>
                            </span>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Tipo</label>
                        <div class="col-10">
                            <select class="form-control" id="type" name="type">
                                <option {{ ( $script->type == "SOAP") ? 'selected' : '' }}>SOAP</option>
                                <option {{ ( $script->type == "RESTful") ? 'selected' : '' }}>RESTful</option>
                                <option {{ ( $script->type == "SSH") ? 'selected' : '' }}>SSH</option>
                                <option {{ ( $script->type == "Gearman") ? 'selected' : '' }}>Gearman</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">API</label>
                        <div class="col-10">
                            <select class="form-control" id="api" name="api">
                                <option {{ ( $script->api == "NuSOAP") ? 'selected' : '' }}>NuSOAP</option>
                                <option {{ ( $script->api == "SLIM") ? 'selected' : '' }}>SLIM</option>
                                <option {{ ( $script->api == "SSH2") ? 'selected' : '' }}>SSH2</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Version</label>
                        <div class="col-10">
                            <input type="numeric" class="form-control form-control-line" id="version" name="version" placeholder="1.00" value="{{ $script->version }}" require>
                        </div>
                    </div>

                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Lenguaje</label>
                        <div class="col-10">
                            <select class="form-control" id="language" name="language">
                                <option {{ ( $script->language == "PHP") ? 'selected' : '' }}>PHP</option>
                                <option {{ ( $script->language == "JAVA") ? 'selected' : '' }}>JAVA</option>
                                <option {{ ( $script->language == "C#") ? 'selected' : '' }}>C#</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">URL</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" id="url" name="url" placeholder="http://localhost" value="{{ $script->url }}" require>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Template</label>
                        <div class="col-3">
                            <select class="form-control" id="template_id" name="template_id" onchange="changeTemplate()">
                                <option value=""> Sin template </option>
                                @foreach ($templates as $template)
                                <option value="{{ $template }}" {{ ( $template->id == $script->template_id) ? 'selected' : '' }}>
                                    {{ $template->name }} </option>
                                @endforeach
                            </select>
                        </div>
                        <label class="col-7 col-form-label" id="template_description">
                            {{ $template->description }}</label>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Actualizar
                            </button>
                            <a href="{{ route('scripts.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/scripts_show.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 text-right">
                        @if ((Auth::user()->can('documents_edit')))
                        <a href="{{ route('scripts.edit', $script->id) }}">
                            <button type="button" class="btn btn-circle btn-primary" onclick="javascript();">
                                <i class="mdi mdi-pencil"></i>
                            </button>
                        </a>
                        @endif
                    </div>
                </div>
                <h4 class="card-title">Detalle del scripts con el id: {{ $script->id }} </h4>
                <h6 class="card-subtitle"> Detalle del <code> scripts</code> y sus parametros.</h6>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Nombre</label>
                    <label class="col-10 col-form-label">{{ $script->name }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Descripción</label>
                    <label class="col-10 col-form-label">{{ $script->description }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Tipo</label>
                    <label class="col-10 col-form-label">{{ $script->type }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">API</label>
                    <label class="col-10 col-form-label">{{ $script->api }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Version</label>
                    <label class="col-10 col-form-label">{{ $script->version }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Lenguaje</label>
                    <label class="col-10 col-form-label">{{ $script->language }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">URL</label>
                    <label class="col-10 col-form-label">{{ $script->url }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Template</label>
                    <!-- Valida que exista un registro si no asigna un valor en blanco -->
                    <label class="col-3 col-form-label">{{ isset($template->name) ? $template->name : '' }}</label>
                    <label class="col-7 col-form-label">{{ isset($template->name) ? $template->description : '' }}</label>
                </div>
                <br>
                <div class="row text-right">
                    <div class="col">
                        <a href="{{ route('scripts.index') }}" class="btn btn-warning">Cancelar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/tools.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justifycontent">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Tools</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div >
                        <table class="table color-table muted-table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Descripción</th>
                                    <th>Creado</th>
                                    <th><i class="fa fa-cog"></i></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($tools as $tool)
                                <tr>
                                    <td>{{ $tool->id }}</td>
                                    <td>{{ $tool->tool }}</td>
                                    <td>{{ $tool->description }}</td>
                                    <td>{{ $tool->created_at }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Opciones
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="#">Action</a>
                                            <a class="dropdown-item" href="#">Another action</a>
                                            <a class="dropdown-item" href="#">Something else here</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $tools->links() }}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection