routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

use App\Http\Controllers\reports\DynamicReportController;
use App\Http\Controllers\reports\ReportController;

Auth::routes();

// --- habilidades, roles, usuarios
Route::get('users-list', 'Admin\UserController@getAll');
Route::get('roles-list', 'Admin\RoleController@getAll');
Route::get('abilities-list', 'Admin\AbilityController@getAll');
//------------------------------------
Route::get('documents-list', 'DocumentController@getAll');
Route::get('scripts-list', 'ScriptController@getAll');
Route::get('devices-list', 'DeviceController@getAll');
Route::post('devices-save', 'DeviceController@save');
Route::post('devices-connect', 'DeviceController@connect');
Route::get('devices-tree-list', 'DeviceTreeController@getTree');

// --- Se crea un prefijo para eliminar el /admin/ de todas las url ---//
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::resource('/users', 'Admin\UserController');
    Route::resource('/roles', 'Admin\RoleController');
    Route::resource('/abilities', 'Admin\AbilityController');
});

// --- Se agrupan para aplicar el middleware de auth ---//
Route::middleware(['auth'])->group(function () {
    Route::get('tools', 'ToolController@index')->name('tools');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/user/profile', 'ProfileController@breadcrumb')->name('profile');
    Route::resource('documents', 'DocumentController');
    Route::resource('devices', 'DeviceController');
    Route::resource('scripts', 'ScriptController');
    /*
     * Trees
     */
    Route::resource('devices-tree', 'DeviceTreeController');
});

// --- Cambiar el lenguaje ---//
Route::get('lang/{locale}', 'LangController@index');
Route::post('document-image-upload', 'DocumentController@imageUpload')->name('image.upload');

// Modificacion de la imagen de perfil del usuario
Route::post('/modificar-img-perfil', 'ImageProfileController@test');

// Reports section
Route::get('/show_reports', [ReportController::class, 'homeReports']);

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{

}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Silber\Bouncer\Database\Ability;
use Silber\Bouncer\Database\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\DB;
use Yajra\Datatables\Datatables;

class RoleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Process ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAll()
    {
        //$this->validaRoleUser('users_manage');
        $roles = Role::all();
        return datatables()->of($roles)->make();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$this->validaRoleUser('users_manage');
        return view('admin.roles.role')->with([
            'title' => 'Roles',
            'breadcrumb' => [
                [
                    'title' => 'Roles'
                ]
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Roles';
        $breadcrumb = [
            [
                'title' => 'Roles',
                'url' => route('roles.index'),
            ],
            [
                'title' => 'Nuevo',
            ],
        ];

        $abilities = Ability::all();
        return view('admin.roles.create')->with(compact('abilities', 'title', 'breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$this->validaRoleUser('users_manage');
        $role = Role::create($request->all());
        $role->allow($request->input('abilities'));
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Detalle';
        $breadcrumb = [
            [
                'title' => 'Detalle',
                'url' => route('roles.index'),
            ],
            [
                'title' => 'Detalle',
            ],
        ];

        return view('admin.roles.show')->with(compact('role', 'title', 'breadcrumb'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Roles';
        $breadcrumb = [
            [
                'title' => 'Roles',
                'url' => route('roles.index'),
            ],
            [
                'title' => 'Editar',
            ],
        ];

        $abilities = Ability::all();
        return view('admin.roles.edit')->with(compact('role', 'abilities', 'title', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        //$this->validaRoleUser('users_manage');
        // Validar datos
        $messages = [];
        $rules = [
            'name' => ['required', 'min:3', ($role->name != $request->name ? 'unique:roles' : '')]
        ];

        $this->validate($request, $rules, $messages);

        $role->update($request->all());
        foreach ($role->getAbilities() as $ability) {
            $role->disallow($ability->name);
        }
        $role->allow($request->input('abilities'));

        $request->session()->flash(
            'notification',
            [
                'type' => 'success',
                'header' => '¡Bien hecho!',
                'message' => 'El rol se actualizó correctamente',
            ]
        );

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //$this->validaRoleUser('users_manage');
        $role->delete();
        return redirect()->route('admin.roles.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        //$this->validaRoleUser('users_manage');
        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();
            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

    /**
     * Valida si el usuario cuenta con la habilidad necesaria.
     *
     * @param String $ability
     */
    public function validaRoleUser($ability)
    {
        if (!Gate::allows($ability)) {
            return abort(401);
        }
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">NUEVO ROL</h4>
                <h6 class="card-subtitle">Para ingresar un nuevo rol debe completar los campos.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('roles.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="administrator" id="name" name="name" value="{{ old('name') }}" require>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Descripción" id="title" name="title" value="{{ old('title') }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Habilidades</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="abilities[]" name="abilities[]" required>
                                @foreach($abilities as $abilitie)
                                <option old('abilities')>{{$abilitie->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Guardar
                            </button>
                            <a href="{{ route('roles.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">EDITAR EL ROL {{ $role->id }} </h4>
                <h6 class="card-subtitle"> Editar rol.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('roles.update', $role->id) }}">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Nombre" id="name" name="name" value="{{ $role->name }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Descripción" id="title" name="title" value="{{ $role->title }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Habilidades</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="abilities[]" name="abilities[]" required>
                                @foreach($abilities as $abilitie)
                                <option old('abilities') @foreach($role->getAbilities()->pluck('id', 'id') as $roleAbilitie)
                                    @if($abilitie->id == $roleAbilitie)
                                    selected = "selected"
                                    @endif
                                    @endforeach>{{$abilitie->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Actualizar
                            </button>
                            <a href="{{ route('roles.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/roles/role.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Roles</h4>-->

                @if (Auth::user()->can('users_manage'))
                <div class="row">
                    <a href="{{ route('roles.create') }}">
                        <button type="button" class="btn btn-rounded btn-primary">Crear nuevo</button>
                    </a>
                </div>
                @endif

                <div class="row">
                    <div class="col">
                        <table class="table color-table  table-responsive table-striped table-hover w-100 d-block d-md-table table-md" id="roles-table"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 text-right">
                        @if ((Auth::user()->can('users_manage')))
                        <a href="{{ route('roles.edit', $role->id) }}">
                            <button type="button" class="btn btn-circle btn-primary" onclick="javascript();">
                                <i class="mdi mdi-pencil"></i>
                            </button>
                        </a>
                        @endif
                    </div>
                </div>
                <h4 class="card-title">DETALLE DEL ROL {{ $role->id }} </h4>
                <h6 class="card-subtitle"> Detalle del rol.</h6>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Nombre</label>
                    <label class="col-10 col-form-label">{{ $role->name }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Descripción</label>
                    <label class="col-10 col-form-label">{{ $role->title }}</label>
                </div>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Habilidades</label>
                    <div class="col-10">
                        @foreach ($role->abilities()->pluck('name') as $ability)
                            <span class="label label-info label-many">{{ $ability }}</span>
                        @endforeach
                    </div>
                </div>
                <br>
                <div class="row text-right">
                    <div class="col">
                        <a href="{{ route('roles.index') }}" class="btn btn-warning">Cancelar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection