routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

use App\Http\Controllers\reports\DynamicReportController;
use App\Http\Controllers\reports\ReportController;

Auth::routes();

// --- habilidades, roles, usuarios
Route::get('users-list', 'Admin\UserController@getAll');
Route::get('roles-list', 'Admin\RoleController@getAll');
Route::get('abilities-list', 'Admin\AbilityController@getAll');
//------------------------------------
Route::get('documents-list', 'DocumentController@getAll');
Route::get('scripts-list', 'ScriptController@getAll');
Route::get('devices-list', 'DeviceController@getAll');
Route::post('devices-save', 'DeviceController@save');
Route::post('devices-connect', 'DeviceController@connect');
Route::get('devices-tree-list', 'DeviceTreeController@getTree');

// --- Se crea un prefijo para eliminar el /admin/ de todas las url ---//
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::resource('/users', 'Admin\UserController');
    Route::resource('/roles', 'Admin\RoleController');
    Route::resource('/abilities', 'Admin\AbilityController');
});

// --- Se agrupan para aplicar el middleware de auth ---//
Route::middleware(['auth'])->group(function () {
    Route::get('tools', 'ToolController@index')->name('tools');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/user/profile', 'ProfileController@breadcrumb')->name('profile');
    Route::resource('documents', 'DocumentController');
    Route::resource('devices', 'DeviceController');
    Route::resource('scripts', 'ScriptController');
    /*
     * Trees
     */
    Route::resource('devices-tree', 'DeviceTreeController');
});

// --- Cambiar el lenguaje ---//
Route::get('lang/{locale}', 'LangController@index');
Route::post('document-image-upload', 'DocumentController@imageUpload')->name('image.upload');

// Modificacion de la imagen de perfil del usuario
Route::post('/modificar-img-perfil', 'ImageProfileController@test');

// Reports section
Route::get('/show_reports', [ReportController::class, 'homeReports']);

app/Ability.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ability extends Model
{

}

app/Http/Controllers/Admin/AbilityController.php
<?php

namespace App\Http\Controllers\Admin;

use Silber\Bouncer\Database\Ability;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\DB;
use Yajra\Datatables\Datatables;

class AbilityController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Process ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAll()
    {
        //$this->validaRoleUser('users_manage');
        $abilities = Ability::all();
        return datatables()->of($abilities)->make(true);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Permisos';
        $breadcrumb = [
            [
                'title' => 'Permisos',
            ]
        ];
        return view('admin.abilities.ability')->with(compact('title', 'breadcrumb'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$this->validaRoleUser('create');
        $title = 'Permisos';
        $breadcrumb = [
            [
                'title' => 'Permisos',
                'url' => route('abilities.index'),
            ],
            [
                'title' => 'Nuevo',
            ],
        ];

        return view('admin.abilities.create')->with(compact('title', 'breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$this->validaRoleUser('users_manage');
        // Validar datos
        $messages = [];
        $rules = [
            'name' => ['required', 'min:3', 'max:20', 'unique:abilities'],
            'title' => ['max:50']
        ];
        $this->validate($request, $rules, $messages);

        Ability::create($request->all());

        $request->session()->flash(
            'notification',
            [
                'type' => 'success',
                'header' => '¡Bien hecho!',
                'message' => 'La habilidad se guardo correctamente',
            ]
        );

        return redirect()->route('abilities.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function show(Ability $ability)
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Detalle';
        $breadcrumb = [
            [
                'title' => 'Detalle',
                'url' => route('abilities.index'),
            ],
            [
                'title' => 'Detalle',
            ],
        ];

        return view('admin.abilities.show')->with(compact('ability', 'title', 'breadcrumb'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function edit(Ability $ability)
    {
        //$this->validaRoleUser('users_manage');
        $title = 'Permisos';
        $breadcrumb = [
            [
                'title' => 'Permisos',
                'url' => route('abilities.index'),
            ],
            [
                'title' => 'Editar',
            ],
        ];

        return view('admin.abilities.edit')->with(compact('ability', 'title', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ability $ability)
    {
        //$this->validaRoleUser('users_manage');
        // Validar datos
        $messages = [];
        $rules = [
            // Case sensitive = strtolower
            'name' => ['required', 'min:3', ($ability->name != $request->name ? 'unique:abilities' : '')]
        ];
        $this->validate($request, $rules, $messages);

        $ability->update($request->all());

        $request->session()->flash(
            'notification',
            [
                'type' => 'success',
                'header' => '¡Bien hecho!',
                'message' => 'El permiso se actualizó correctamente',
            ]
        );

        return redirect()->route('abilities.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ability  $ability
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ability $ability)
    {
        //$this->validaRoleUser('users_manage');
        $ability->delete();
        return redirect()->route('admin.abilities.index');
    }

    /**
     * Delete all selected Ability at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        //$this->validaRoleUser('users_manage');
        if ($request->input('ids')) {
            $entries = Ability::whereIn('id', $request->input('ids'))->get();
            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

    /**
     * Valida si el usuario cuenta con la habilidad necesaria.
     *
     * @param String $ability
     */
    public function validaRoleUser($ability)
    {
        if (!Gate::allows($ability)) {
            return abort(401);
        }
    }
}

resources/views/admin/abilities/ability.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Habilidades</h4>-->

                @if (Auth::user()->can('users_manage'))
                    <div class="row">
                        <a href="{{ route('abilities.create') }}">
                            <button type="button" class="btn btn-rounded btn-primary">Crear nuevo</button>
                        </a>
                    </div>                                   
                @endif

                <div class="row">
                    <div class="col">
                        <table class="table color-table  table-responsive table-striped table-hover w-100 d-block d-md-table table-md" id="abilities-table"></table>    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/abilities/create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">NUEVO PERMISO</h4>
                <h6 class="card-subtitle"> Para ingresar un nuevo permiso debe completar los campos.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('abilities.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="nombre"
                                id="name" name="name" value="{{ old('name') }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Descripción"
                                id="title" name="title" value="{{ old('title') }}" required>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Guardar
                            </button>
                            <a href="{{ route('abilities.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/abilities/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">EDITAR PERMISO: {{ $ability->id }} </h4>
                <h6 class="card-subtitle">Editar el permiso..</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('abilities.update', $ability->id) }}">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Nombre" id="name" name="name" value="{{ $ability->name }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Descripción</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Descripción" id="title" name="title" value="{{ $ability->title }}" required>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Actualizar
                            </button>
                            <a href="{{ route('abilities.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/abilities/show.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 text-right">
                        @if ((Auth::user()->can('users_manage')))
                        <a href="{{ route('abilities.edit', $ability->id) }}">
                            <button type="button" class="btn btn-circle btn-primary" onclick="javascript();">
                                <i class="mdi mdi-pencil"></i>
                            </button>
                        </a>
                        @endif
                    </div>
                </div>
                <h4 class="card-title">Detalle del permiso: {{ $ability->id }} </h4>
                <h6 class="card-subtitle"> Detalle del permiso.</h6>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Nombre</label>
                    <label class="col-10 col-form-label">{{ $ability->name }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Descripción</label>
                    <label class="col-10 col-form-label">{{ $ability->title }}</label> 
                </div>             
                <br>
                <div class="row text-right">
                    <div class="col">
                        <a href="{{ route('abilities.index') }}" class="btn btn-warning">Cancelar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection