routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

use App\Http\Controllers\reports\DynamicReportController;
use App\Http\Controllers\reports\ReportController;

Auth::routes();

// --- habilidades, roles, usuarios
Route::get('users-list', 'Admin\UserController@getAll');
Route::get('roles-list', 'Admin\RoleController@getAll');
Route::get('abilities-list', 'Admin\AbilityController@getAll');
//------------------------------------
Route::get('documents-list', 'DocumentController@getAll');
Route::get('scripts-list', 'ScriptController@getAll');
Route::get('devices-list', 'DeviceController@getAll');
Route::post('devices-save', 'DeviceController@save');
Route::post('devices-connect', 'DeviceController@connect');
Route::get('devices-tree-list', 'DeviceTreeController@getTree');

// --- Se crea un prefijo para eliminar el /admin/ de todas las url ---//
Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::resource('/users', 'Admin\UserController');
    Route::resource('/roles', 'Admin\RoleController');
    Route::resource('/abilities', 'Admin\AbilityController');
});

// --- Se agrupan para aplicar el middleware de auth ---//
Route::middleware(['auth'])->group(function () {
    Route::get('tools', 'ToolController@index')->name('tools');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/user/profile', 'ProfileController@breadcrumb')->name('profile');
    Route::resource('documents', 'DocumentController');
    Route::resource('devices', 'DeviceController');
    Route::resource('scripts', 'ScriptController');
    /*
     * Trees
     */
    Route::resource('devices-tree', 'DeviceTreeController');
});

// --- Cambiar el lenguaje ---//
Route::get('lang/{locale}', 'LangController@index');
Route::post('document-image-upload', 'DocumentController@imageUpload')->name('image.upload');

// Modificacion de la imagen de perfil del usuario
Route::post('/modificar-img-perfil', 'ImageProfileController@test');

// Reports section
Route::get('/show_reports', [ReportController::class, 'homeReports']);

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Hash;

/**
 * Class User
 *
 * @package App
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 */
class User extends Authenticatable
{
    use Notifiable;
    use HasRolesAndAbilities;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Obtiene los documentos propiedad de un usuario.
     */
    public function documents()
    {
        return $this->hasMany(Document::class);
    }

    /**
     * Hash password
     * @param $input
     */
    public function setPasswordAttribute($input)
    {
        if ($input)
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    }

    /**
     * TODO. Documentar.
     */
    public function role()
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Silber\Bouncer\Database\Ability;
use Silber\Bouncer\Database\Role;
use Illuminate\Support\Facades\DB;
use Yajra\Datatables\Datatables;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Process ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAll()
    {
        $users = User::all();
        return datatables()->of($users)->make();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.user')->with([
            'title' => 'Usuarios',
            'breadcrumb' => [
                [
                    'title' => 'Usuarios'
                ]
            ]
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $title = 'Usuario';
        $breadcrumb = [
            [
                'title' => 'Usuario',
                'url' => route('users.index'),
            ],
            [
                'title' => 'Nuevo',
            ],
        ];

        $abilities = Ability::all();
        $roles = Role::all();
        return view('admin.users.create')->with(compact('roles', 'abilities', 'title', 'breadcrumb'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validar datos
        $messages = [];
        $rules = [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:6', 'confirmed']
        ];

        $this->validate($request, $rules, $messages);

        $user = User::create($request->all());
        // --- Asignar un rol al usuario
        foreach ($request->input('roles') as $role) {
            $user->assign($role);
        }
        // --- Aplicar habilidad a un usuario
        $abilities = $request->input('abilities');
        if ($abilities) {
            foreach ($abilities as $abilitie) {
                $user->allow($abilitie);
            }
        }
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $title = 'Detalle';
        $breadcrumb = [
            [
                'title' => 'Detalle',
                'url' => route('users.index'),
            ],
            [
                'title' => 'Detalle',
            ],
        ];

        return view('admin.users.show')->with(compact('user', 'title', 'breadcrumb'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $title = 'Usuarios';
        $breadcrumb = [
            [
                'title' => 'Usuarios',
                'url' => route('users.index'),
            ],
            [
                'title' => 'Editar',
            ],
        ];

        $roles = Role::all();
        $abilities = Ability::all();
        return view('admin.users.edit')->with(compact('user', 'roles', 'abilities', 'title', 'breadcrumb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        // Validar datos
        $messages = [];
        $rules = [
            'email' => ['required', ($user->email != $request->email ? 'unique:users' : '')]
        ];

        $this->validate($request, $rules, $messages);

        $user->update($request->all());
        // --- Roles
        foreach ($user->roles as $role) {
            $user->retract($role);
        }
        $user->assign($request->input('roles'));
        // --- Habilidades
        foreach ($user->getAbilities() as $ability) {
            $user->disallow($ability->name);
        }
        $user->allow($request->input('abilities'));

        $request->session()->flash(
            'notification',
            [
                'type' => 'success',
                'header' => '¡Bien hecho!',
                'message' => 'El usuario se actualizó correctamente',
            ]
        );

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.users.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();
            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">NUEVO USUARIO</h4>
                <h6 class="card-subtitle">Para ingresar un nuevo usuario debe completar los campos.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('users.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="nombre" id="name" name="name" value="{{ old('name') }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Email</label>
                        <div class="col-10">
                            <input type="email" class="form-control form-control-line" placeholder="email@email.com" id="email" name="email" value="{{ old('email') }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Password</label>
                        <div class="col-10">
                            <input type="password" class="form-control form-control-line" placeholder="password" id="password" name="password" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Confirmar Password</label>
                        <div class="col-10">
                            <input type="password" class="form-control form-control-line" placeholder="confirmar password" id="password_confirmation" name="password_confirmation" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Roles</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="roles[]" name="roles[]" required>
                                @foreach($roles as $role)
                                <option old('roles')>{{$role->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Permisos</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="abilities[]" name="abilities[]">
                                @foreach($abilities as $abilitie)
                                <option old('abilities')>{{$abilitie->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Guardar
                            </button>
                            <a href="{{ route('users.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <h4 class="card-title">Editar el usuario: {{ $user->id }} </h4>
                <h6 class="card-subtitle">Editar el usuario.</h6>
                <form class="form-material m-t-40" method="POST" action="{{ route('users.update', $user->id) }}">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Nombre</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="Nombre" id="name" name="name" value="{{ $user->name }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Email</label>
                        <div class="col-10">
                            <input type="text" class="form-control form-control-line" placeholder="email" id="editEmail" name="email" value="{{ $user->email }}" required>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Roles</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="roles[]" name="roles[]" required>
                                @foreach($roles as $role)
                                <option old('roles') @foreach($user->roles()->pluck('id', 'id') as $roleUser)
                                    @if($role->id == $roleUser)
                                    selected = "selected"
                                    @endif
                                    @endforeach>{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group m-t-40 row">
                        <label class="col-2 col-form-label text-right">Permisos</label>
                        <div class="col-10">
                            <select class="select2 select2-multiple" style="width: 100%" multiple="multiple" data-placeholder="Choose" id="abilities[]" name="abilities[]">
                                @foreach($abilities as $abilitie)
                                <option old('abilities') @foreach($user->abilities->pluck('id', 'id') as $roleAbilitie)
                                    @if($abilitie->id == $roleAbilitie)
                                    selected = "selected"
                                    @endif
                                    @endforeach>{{ $abilitie->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row text-right">
                        <div class="col">
                            <button type="submit" class="btn btn-success" id="save">
                                Actualizar
                            </button>
                            <a href="{{ route('users.index') }}" class="btn btn-warning">Cancelar </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 text-right">
                        @if ((Auth::user()->can('users_manage')))
                        <a href="{{ route('users.edit', $user->id) }}">
                            <button type="button" class="btn btn-circle btn-primary" onclick="javascript();">
                                <i class="mdi mdi-pencil"></i>
                            </button>
                        </a>
                        @endif
                    </div>
                </div>
                <h4 class="card-title">Detalle del usuario: {{ $user->id }} </h4>
                <h6 class="card-subtitle"> Detalle del usuario.</h6>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Nombre</label>
                    <label class="col-10 col-form-label">{{ $user->name }}</label>
                </div>
                <div class="form-group m-t-10 row">
                    <label class="col-2 col-form-label text-right">Email</label>
                    <label class="col-10 col-form-label">{{ $user->email }}</label>
                </div>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Roles</label>
                    <div class="col-10">
                        @foreach ($user->roles()->pluck('name') as $role)
                            <span class="label label-info label-many">{{ $role }}</span>
                        @endforeach
                    </div>
                </div>
                <div class="form-group m-t-40 row">
                    <label class="col-2 col-form-label text-right">Permisos</label>
                    <div class="col-10">
                        @foreach ($user->abilities->pluck('name') as $ability)
                            <span class="label label-info label-many">{{ $ability }}</span>
                        @endforeach
                    </div>
                </div>
                <br>
                <div class="row text-right">
                    <div class="col">
                        <a href="{{ route('users.index') }}" class="btn btn-warning">Cancelar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/users/user.blade.php
@extends('layouts.master')

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <!--<h4 class="card-title">Usuarios</h4>-->

                @if (Auth::user()->can('users_manage'))
                    <div class="row">
                        <a href="{{ route('users.create') }}">
                            <button type="button" class="btn btn-rounded btn-primary">Crear nuevo</button>
                        </a>
                    </div>                                   
                @endif

                <div class="row">
                    <div class="col">    
                        <table class="table color-table  table-responsive table-striped table-hover w-100 d-block d-md-table table-md" id="users-table"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection